name: 'Paul Pacheco'
description: 'Github action for publishing nunit results as github checks'
author: 'MirrorNG'
inputs:
  access-token:
    description: 'github token'
    required: true
  path:
    description: 'glob to junit xml files'
    required: true
  numFailures:
    description: 'max number of failed tests to include'
    require: true
    default: 30
runs:
  using: 'node12'
  main: 'dist/index.js'
