name: "build-test"
on: # rebuild any PRs and main branch changes
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm run all
        
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with: 
        path: '*.xml'
        access-token: ${{secrets.GITHUB_TOKEN}}
    - name: Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
